In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
file_path = os.path.expanduser("~/Desktop/auto_loan_securitisation_data.csv")
df = pd.read_csv(file_path)
df

,LoanID,PoolID,BorrowerID,ServicerID,ServicerName,OriginationChannel,OriginationDate,CutoffDate,MaturityDate,OriginalLoanAmount,...,ECL_Provision,IsDefaulted,IsModified,ModificationType,LossAmount,RecoveryAmount,NetLoss,PrepaymentAmount,InsuranceType,HasInsurance
0,ZAAUTO2024-1-00001,ZAAUTO2024-1,BOR-131244,SVC001,HDFC Bank Auto Finance,Direct,2024-08-02,2024-10-31,2031-06-27,782300.0,...,7507.75,False,False,NaN,0.0,0.0,0.0,0.0,Comprehensive,True
1,ZAAUTO2024-1-00002,ZAAUTO2024-1,BOR-748564,SVC003,Bajaj Finance Auto,Online,2024-05-21,2024-10-31,2027-05-06,772400.0,...,8502.42,False,False,NaN,0.0,0.0,0.0,0.0,Comprehensive,True
2,ZAAUTO2024-1-00003,ZAAUTO2024-1,BOR-694731,SVC002,ICICI Auto Loans,Online,2024-08-03,2024-10-31,2029-07-08,333100.0,...,3238.45,False,False,NaN,0.0,0.0,0.0,0.0,Comprehensive,True
3,ZAAUTO2024-1-00004,ZAAUTO2024-1,BOR-855731,SVC003,Bajaj Finance Auto,Online,2023-05-15,2024-10-31,2030-04-08,1410200.0,...,12400.16,False,False,NaN,0.0,0.0,0.0,0.0,Nil,True
4,ZAAUTO2024-1-00005,ZAAUTO2024-1,BOR-897549,SVC003,Bajaj Finance Auto,Online,2021-08-18,2024-10-31,2024-08-02,1703600.0,...,0.00,False,False,NaN,0.0,0.0,0.0,0.0,Nil,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ZAAUTO2024-1-00496,ZAAUTO2024-1,BOR-130294,SVC002,ICICI Auto Loans,Online,2022-11-28,2024-10-31,2026-11-07,2694800.0,...,54545.44,False,False,NaN,0.0,0.0,0.0,0.0,Comprehensive,True
496,ZAAUTO2024-1-00497,ZAAUTO2024-1,BOR-208691,SVC003,Bajaj Finance Auto,Dealer,2023-07-15,2024-10-31,2028-06-18,1060500.0,...,6444.10,False,False,NaN,0.0,0.0,0.0,0.0,Nil,True
497,ZAAUTO2024-1-00498,ZAAUTO2024-1,BOR-375903,SVC002,ICICI Auto Loans,DSA,2024-05-04,2024-10-31,2028-04-13,793700.0,...,8696.41,False,False,NaN,0.0,0.0,0.0,0.0,Nil,False
498,ZAAUTO2024-1-00499,ZAAUTO2024-1,BOR-366825,SVC003,Bajaj Finance Auto,DSA,2021-12-25,2024-10-31,2024-12-09,723800.0,...,518.95,False,False,NaN,0.0,0.0,0.0,0.0,Third Party,True
499,ZAAUTO2024-1-00500,ZAAUTO2024-1,BOR-597793,SVC003,Bajaj Finance Auto,Direct,2024-08-14,2024-10-31,2030-07-14,1441600.0,...,15494.59,False,False,NaN,0.0,0.0,0.0,0.0,Comprehensive,True

In [3]:
df.head()

,LoanID,PoolID,BorrowerID,ServicerID,ServicerName,OriginationChannel,OriginationDate,CutoffDate,MaturityDate,OriginalLoanAmount,...,ECL_Provision,IsDefaulted,IsModified,ModificationType,LossAmount,RecoveryAmount,NetLoss,PrepaymentAmount,InsuranceType,HasInsurance
0,ZAAUTO2024-1-00001,ZAAUTO2024-1,BOR-131244,SVC001,HDFC Bank Auto Finance,Direct,2024-08-02,2024-10-31,2031-06-27,782300.0,...,7507.75,False,False,NaN,0.0,0.0,0.0,0.0,Comprehensive,True
1,ZAAUTO2024-1-00002,ZAAUTO2024-1,BOR-748564,SVC003,Bajaj Finance Auto,Online,2024-05-21,2024-10-31,2027-05-06,772400.0,...,8502.42,False,False,NaN,0.0,0.0,0.0,0.0,Comprehensive,True
2,ZAAUTO2024-1-00003,ZAAUTO2024-1,BOR-694731,SVC002,ICICI Auto Loans,Online,2024-08-03,2024-10-31,2029-07-08,333100.0,...,3238.45,False,False,NaN,0.0,0.0,0.0,0.0,Comprehensive,True
3,ZAAUTO2024-1-00004,ZAAUTO2024-1,BOR-855731,SVC003,Bajaj Finance Auto,Online,2023-05-15,2024-10-31,2030-04-08,1410200.0,...,12400.16,False,False,NaN,0.0,0.0,0.0,0.0,Nil,True
4,ZAAUTO2024-1-00005,ZAAUTO2024-1,BOR-897549,SVC003,Bajaj Finance Auto,Online,2021-08-18,2024-10-31,2024-08-02,1703600.0,...,0.00,False,False,NaN,0.0,0.0,0.0,0.0,Nil,True

In [4]:
df.columns

Index(['LoanID', 'PoolID', 'BorrowerID', 'ServicerID', 'ServicerName',
       'OriginationChannel', 'OriginationDate', 'CutoffDate', 'MaturityDate',
       'OriginalLoanAmount', 'OriginalTerm', 'RemainingTerm', 'MonthsOnBook',
       'InterestRate', 'MonthlyEMI', 'LoanPurpose', 'CurrentBalance',
       'ScheduledPaymentDue', 'LastPaymentAmount', 'LastPaymentDate',
       'DelinquencyStatus', 'DelinquencyDays', 'TotalPaymentsDue',
       'TotalPaymentsMade', 'Times30DPD_Last12M', 'Times60DPD_Last12M',
       'Times90DPD_Last12M', 'VehicleMake', 'VehicleModel', 'VehicleYear',
       'VehicleType', 'IsNewVehicle', 'OriginalVehicleValue',
       'CurrentVehicleValue', 'LTV_AtOrigination', 'LTV_Current',
       'BorrowerAge', 'EmploymentType', 'AnnualIncome_INR', 'DTI_Ratio',
       'CIBIL_Score_Origination', 'CIBIL_Score_Current', 'Region', 'State',
       'IFRS9_Stage', 'PD_Estimate', 'LGD_Estimate', 'EAD', 'ECL_Provision',
       'IsDefaulted', 'IsModified', 'ModificationType', 'LossAmount',
       'RecoveryAmount', 'NetLoss', 'PrepaymentAmount', 'InsuranceType',
       'HasInsurance'],
      dtype='object')

In [5]:
df.isnull().sum()

LoanID                       0
PoolID                       0
BorrowerID                   0
ServicerID                   0
ServicerName                 0
OriginationChannel           0
OriginationDate              0
CutoffDate                   0
MaturityDate                 0
OriginalLoanAmount           0
OriginalTerm                 0
RemainingTerm                0
MonthsOnBook                 0
InterestRate                 0
MonthlyEMI                   0
LoanPurpose                  0
CurrentBalance               0
ScheduledPaymentDue          0
LastPaymentAmount            0
LastPaymentDate              0
DelinquencyStatus            0
DelinquencyDays              0
TotalPaymentsDue             0
TotalPaymentsMade            0
Times30DPD_Last12M           0
Times60DPD_Last12M           0
Times90DPD_Last12M           0
VehicleMake                  0
VehicleModel                 0
VehicleYear                  0
VehicleType                  0
IsNewVehicle                 0
OriginalVehicleValue         0
CurrentVehicleValue          0
LTV_AtOrigination            0
LTV_Current                  0
BorrowerAge                  0
EmploymentType               0
AnnualIncome_INR             0
DTI_Ratio                    0
CIBIL_Score_Origination      0
CIBIL_Score_Current          0
Region                       0
State                        0
IFRS9_Stage                  0
PD_Estimate                  0
LGD_Estimate                 0
EAD                          0
ECL_Provision                0
IsDefaulted                  0
IsModified                   0
ModificationType           481
LossAmount                   0
RecoveryAmount               0
NetLoss                      0
PrepaymentAmount             0
InsuranceType                0
HasInsurance                 0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["ModificationType"] = df["ModificationType"].fillna("No Modification")
df

,LoanID,PoolID,BorrowerID,ServicerID,ServicerName,OriginationChannel,OriginationDate,CutoffDate,MaturityDate,OriginalLoanAmount,...,ECL_Provision,IsDefaulted,IsModified,ModificationType,LossAmount,RecoveryAmount,NetLoss,PrepaymentAmount,InsuranceType,HasInsurance
0,ZAAUTO2024-1-00001,ZAAUTO2024-1,BOR-131244,SVC001,HDFC Bank Auto Finance,Direct,2024-08-02,2024-10-31,2031-06-27,782300.0,...,7507.75,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True
1,ZAAUTO2024-1-00002,ZAAUTO2024-1,BOR-748564,SVC003,Bajaj Finance Auto,Online,2024-05-21,2024-10-31,2027-05-06,772400.0,...,8502.42,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True
2,ZAAUTO2024-1-00003,ZAAUTO2024-1,BOR-694731,SVC002,ICICI Auto Loans,Online,2024-08-03,2024-10-31,2029-07-08,333100.0,...,3238.45,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True
3,ZAAUTO2024-1-00004,ZAAUTO2024-1,BOR-855731,SVC003,Bajaj Finance Auto,Online,2023-05-15,2024-10-31,2030-04-08,1410200.0,...,12400.16,False,False,No Modification,0.0,0.0,0.0,0.0,Nil,True
4,ZAAUTO2024-1-00005,ZAAUTO2024-1,BOR-897549,SVC003,Bajaj Finance Auto,Online,2021-08-18,2024-10-31,2024-08-02,1703600.0,...,0.00,False,False,No Modification,0.0,0.0,0.0,0.0,Nil,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ZAAUTO2024-1-00496,ZAAUTO2024-1,BOR-130294,SVC002,ICICI Auto Loans,Online,2022-11-28,2024-10-31,2026-11-07,2694800.0,...,54545.44,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True
496,ZAAUTO2024-1-00497,ZAAUTO2024-1,BOR-208691,SVC003,Bajaj Finance Auto,Dealer,2023-07-15,2024-10-31,2028-06-18,1060500.0,...,6444.10,False,False,No Modification,0.0,0.0,0.0,0.0,Nil,True
497,ZAAUTO2024-1-00498,ZAAUTO2024-1,BOR-375903,SVC002,ICICI Auto Loans,DSA,2024-05-04,2024-10-31,2028-04-13,793700.0,...,8696.41,False,False,No Modification,0.0,0.0,0.0,0.0,Nil,False
498,ZAAUTO2024-1-00499,ZAAUTO2024-1,BOR-366825,SVC003,Bajaj Finance Auto,DSA,2021-12-25,2024-10-31,2024-12-09,723800.0,...,518.95,False,False,No Modification,0.0,0.0,0.0,0.0,Third Party,True
499,ZAAUTO2024-1-00500,ZAAUTO2024-1,BOR-597793,SVC003,Bajaj Finance Auto,Direct,2024-08-14,2024-10-31,2030-07-14,1441600.0,...,15494.59,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 58 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   LoanID                   500 non-null    object
 1   PoolID                   500 non-null    object
 2   BorrowerID               500 non-null    object
 3   ServicerID               500 non-null    object
 4   ServicerName             500 non-null    object
 5   OriginationChannel       500 non-null    object
 6   OriginationDate          500 non-null    object
 7   CutoffDate               500 non-null    object
 8   MaturityDate             500 non-null    object
 9   OriginalLoanAmount       500 non-null    float64
 10  OriginalTerm             500 non-null    int64
 11  RemainingTerm            500 non-null    int64
 12  MonthsOnBook             500 non-null    int64
 13  InterestRate             500 non-null    float64
 14  MonthlyEMI               500 non-null    float64
 15  LoanPurpose              500 non-null    object
 16  CurrentBalance           500 non-null    float64
 17  ScheduledPaymentDue      500 non-null    float64
 18  LastPaymentAmount        500 non-null    float64
 19  LastPaymentDate          500 non-null    object
 20  DelinquencyStatus        500 non-null    object
 21  DelinquencyDays          500 non-null    int64
 22  TotalPaymentsDue         500 non-null    int64
 23  TotalPaymentsMade        500 non-null    int64
 24  Times30DPD_Last12M       500 non-null    int64
 25  Times60DPD_Last12M       500 non-null    int64
 26  Times90DPD_Last12M       500 non-null    int64
 27  VehicleMake              500 non-null    object
 28  VehicleModel             500 non-null    object
 29  VehicleYear              500 non-null    int64
 30  VehicleType              500 non-null    object
 31  IsNewVehicle             500 non-null    bool
 32  OriginalVehicleValue     500 non-null    float64
 33  CurrentVehicleValue      500 non-null    float64
 34  LTV_AtOrigination        500 non-null    float64
 35  LTV_Current              500 non-null    float64
 36  BorrowerAge              500 non-null    int64
 37  EmploymentType           500 non-null    object
 38  AnnualIncome_INR         500 non-null    float64
 39  DTI_Ratio                500 non-null    float64
 40  CIBIL_Score_Origination  500 non-null    int64
 41  CIBIL_Score_Current      500 non-null    int64
 42  Region                   500 non-null    object
 43  State                    500 non-null    object
 44  IFRS9_Stage              500 non-null    int64
 45  PD_Estimate              500 non-null    float64
 46  LGD_Estimate             500 non-null    float64
 47  EAD                      500 non-null    float64
 48  ECL_Provision            500 non-null    float64
 49  IsDefaulted              500 non-null    bool
 50  IsModified               500 non-null    bool
 51  ModificationType         500 non-null    object
 52  LossAmount               500 non-null    float64
 53  RecoveryAmount           500 non-null    float64
 54  NetLoss                  500 non-null    float64
 55  PrepaymentAmount         500 non-null    float64
 56  InsuranceType            500 non-null    object
 57  HasInsurance             500 non-null    bool
dtypes: bool(4), float64(20), int64(14), object(20)
memory usage: 213.0+ KB

In [11]:
date_columns = ["OriginationDate", "CutoffDate", "MaturityDate", "LastPaymentDate"]

for col in date_columns:
    df[col] = pd.to_datetime(df[col])
df

,LoanID,PoolID,BorrowerID,ServicerID,ServicerName,OriginationChannel,OriginationDate,CutoffDate,MaturityDate,OriginalLoanAmount,...,ECL_Provision,IsDefaulted,IsModified,ModificationType,LossAmount,RecoveryAmount,NetLoss,PrepaymentAmount,InsuranceType,HasInsurance
0,ZAAUTO2024-1-00001,ZAAUTO2024-1,BOR-131244,SVC001,HDFC Bank Auto Finance,Direct,2024-08-02,2024-10-31,2031-06-27,782300.0,...,7507.75,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True
1,ZAAUTO2024-1-00002,ZAAUTO2024-1,BOR-748564,SVC003,Bajaj Finance Auto,Online,2024-05-21,2024-10-31,2027-05-06,772400.0,...,8502.42,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True
2,ZAAUTO2024-1-00003,ZAAUTO2024-1,BOR-694731,SVC002,ICICI Auto Loans,Online,2024-08-03,2024-10-31,2029-07-08,333100.0,...,3238.45,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True
3,ZAAUTO2024-1-00004,ZAAUTO2024-1,BOR-855731,SVC003,Bajaj Finance Auto,Online,2023-05-15,2024-10-31,2030-04-08,1410200.0,...,12400.16,False,False,No Modification,0.0,0.0,0.0,0.0,Nil,True
4,ZAAUTO2024-1-00005,ZAAUTO2024-1,BOR-897549,SVC003,Bajaj Finance Auto,Online,2021-08-18,2024-10-31,2024-08-02,1703600.0,...,0.00,False,False,No Modification,0.0,0.0,0.0,0.0,Nil,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ZAAUTO2024-1-00496,ZAAUTO2024-1,BOR-130294,SVC002,ICICI Auto Loans,Online,2022-11-28,2024-10-31,2026-11-07,2694800.0,...,54545.44,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True
496,ZAAUTO2024-1-00497,ZAAUTO2024-1,BOR-208691,SVC003,Bajaj Finance Auto,Dealer,2023-07-15,2024-10-31,2028-06-18,1060500.0,...,6444.10,False,False,No Modification,0.0,0.0,0.0,0.0,Nil,True
497,ZAAUTO2024-1-00498,ZAAUTO2024-1,BOR-375903,SVC002,ICICI Auto Loans,DSA,2024-05-04,2024-10-31,2028-04-13,793700.0,...,8696.41,False,False,No Modification,0.0,0.0,0.0,0.0,Nil,False
498,ZAAUTO2024-1-00499,ZAAUTO2024-1,BOR-366825,SVC003,Bajaj Finance Auto,DSA,2021-12-25,2024-10-31,2024-12-09,723800.0,...,518.95,False,False,No Modification,0.0,0.0,0.0,0.0,Third Party,True
499,ZAAUTO2024-1-00500,ZAAUTO2024-1,BOR-597793,SVC003,Bajaj Finance Auto,Direct,2024-08-14,2024-10-31,2030-07-14,1441600.0,...,15494.59,False,False,No Modification,0.0,0.0,0.0,0.0,Comprehensive,True

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 58 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   LoanID                   500 non-null    object
 1   PoolID                   500 non-null    object
 2   BorrowerID               500 non-null    object
 3   ServicerID               500 non-null    object
 4   ServicerName             500 non-null    object
 5   OriginationChannel       500 non-null    object
 6   OriginationDate          500 non-null    datetime64[ns]
 7   CutoffDate               500 non-null    datetime64[ns]
 8   MaturityDate             500 non-null    datetime64[ns]
 9   OriginalLoanAmount       500 non-null    float64
 10  OriginalTerm             500 non-null    int64
 11  RemainingTerm            500 non-null    int64
 12  MonthsOnBook             500 non-null    int64
 13  InterestRate             500 non-null    float64
 14  MonthlyEMI               500 non-null    float64
 15  LoanPurpose              500 non-null    object
 16  CurrentBalance           500 non-null    float64
 17  ScheduledPaymentDue      500 non-null    float64
 18  LastPaymentAmount        500 non-null    float64
 19  LastPaymentDate          500 non-null    datetime64[ns]
 20  DelinquencyStatus        500 non-null    object
 21  DelinquencyDays          500 non-null    int64
 22  TotalPaymentsDue         500 non-null    int64
 23  TotalPaymentsMade        500 non-null    int64
 24  Times30DPD_Last12M       500 non-null    int64
 25  Times60DPD_Last12M       500 non-null    int64
 26  Times90DPD_Last12M       500 non-null    int64
 27  VehicleMake              500 non-null    object
 28  VehicleModel             500 non-null    object
 29  VehicleYear              500 non-null    int64
 30  VehicleType              500 non-null    object
 31  IsNewVehicle             500 non-null    bool
 32  OriginalVehicleValue     500 non-null    float64
 33  CurrentVehicleValue      500 non-null    float64
 34  LTV_AtOrigination        500 non-null    float64
 35  LTV_Current              500 non-null    float64
 36  BorrowerAge              500 non-null    int64
 37  EmploymentType           500 non-null    object
 38  AnnualIncome_INR         500 non-null    float64
 39  DTI_Ratio                500 non-null    float64
 40  CIBIL_Score_Origination  500 non-null    int64
 41  CIBIL_Score_Current      500 non-null    int64
 42  Region                   500 non-null    object
 43  State                    500 non-null    object
 44  IFRS9_Stage              500 non-null    int64
 45  PD_Estimate              500 non-null    float64
 46  LGD_Estimate             500 non-null    float64
 47  EAD                      500 non-null    float64
 48  ECL_Provision            500 non-null    float64
 49  IsDefaulted              500 non-null    bool
 50  IsModified               500 non-null    bool
 51  ModificationType         500 non-null    object
 52  LossAmount               500 non-null    float64
 53  RecoveryAmount           500 non-null    float64
 54  NetLoss                  500 non-null    float64
 55  PrepaymentAmount         500 non-null    float64
 56  InsuranceType            500 non-null    object
 57  HasInsurance             500 non-null    bool
dtypes: bool(4), datetime64[ns](4), float64(20), int64(14), object(16)
memory usage: 213.0+ KB

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df["DelinquencyStatus"].value_counts()

DelinquencyStatus
Current        385
1-29 DPD        37
60-89 DPD       24
30-59 DPD       21
120+ DPD        14
90-119 DPD      10
Default          7
Repossessed      2
Name: count, dtype: int64

In [15]:
df["LoanPurpose"].value_counts()

LoanPurpose
New Vehicle Purchase     419
Used Vehicle Purchase     48
Refinance                 33
Name: count, dtype: int64

In [35]:
import os
print(os.getcwd())

/Users/kavyagodala

In [36]:
df.to_csv("cleaned_auto_loan_data.csv", index=False)
print("File Saved Successfully")

File Saved Successfully